[package]
name = "svdp"
version = "0.1.0"
authors = ["test <test@test>"]

[dependencies]
postgres = "0.15.1"
hyper = "0.11.18"
clap = "2.29.4"

serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
