[package]
name = "svdp"
version = "0.1.0"
authors = ["test <test@test>"]

[dependencies]
clap = "2.29.4"

postgres = "0.15.1"
r2d2_postgres = "0.14.0"

reqwest = "0.8.4"

serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
